# Generated by Django 4.2.8 on 2023-12-07 18:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postattachment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objetcs', django.db.models.manager.Manager()),
            ],
        ),
    ]
